AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: chapter5-data-pipeline

Globals:
  Function:
    Runtime: java8
    MemorySize: 512
    Timeout: 10
Resources:
 Resources:
  PipelineStartBucket:
   Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub hemantlambdatestbucket-start
  FanOutTopic:
    Type: AWS::SNS::Topic

  BulkEventsLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/DemoJava-0.0.1-SNAPSHOT.jar
      Handler: com.amazonaws.handler.GetOrderHandler::handleRequest
      Environment:
        Variables:
          FAN_OUT_TOPIC: !Ref FanOutTopic
      Policies:
      - S3ReadPolicy:
          BucketName: !Sub hemantlambdatestbucket-start
      - SNSPublishMessagePolicy:
          TopicName: !GetAtt FanOutTopic.TopicName
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PipelineStartBucket
            Events: s3:ObjectCreated:*

  SingleEventLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/DemoJava-0.0.1-SNAPSHOT.jar
      Handler: com.amazonaws.handler.GetOrderHandler::handleRequest
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: !Ref FanOutTopic
